/**
 * Badges
 * Badges API allows you to create Badges rules that can be applied to particular users.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@impossiblemissionsforce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Badges);
  }
}(this, function(expect, Badges) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Badges.RequirementInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RequirementInner', function() {
    it('should create an instance of RequirementInner', function() {
      // uncomment below and update the code to test RequirementInner
      //var instance = new Badges.RequirementInner();
      //expect(instance).to.be.a(Badges.RequirementInner);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Badges.RequirementInner();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Badges.RequirementInner();
      //expect(instance).to.be();
    });

    it('should have the property minScore (base name: "minScore")', function() {
      // uncomment below and update the code to test the property minScore
      //var instance = new Badges.RequirementInner();
      //expect(instance).to.be();
    });

    it('should have the property maxAttempts (base name: "maxAttempts")', function() {
      // uncomment below and update the code to test the property maxAttempts
      //var instance = new Badges.RequirementInner();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new Badges.RequirementInner();
      //expect(instance).to.be();
    });

  });

}));
