/**
 * Assignments
 * API to assign checklist or quiz to user.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: blips-and-chitze@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Assignments);
  }
}(this, function(expect, Assignments) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Assignments.Assignment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Assignment', function() {
    it('should create an instance of Assignment', function() {
      // uncomment below and update the code to test Assignment
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be.a(Assignments.Assignment);
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be();
    });

    it('should have the property deadline (base name: "deadline")', function() {
      // uncomment below and update the code to test the property deadline
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be();
    });

    it('should have the property maxAttempts (base name: "maxAttempts")', function() {
      // uncomment below and update the code to test the property maxAttempts
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be();
    });

    it('should have the property assignedAt (base name: "assignedAt")', function() {
      // uncomment below and update the code to test the property assignedAt
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be();
    });

    it('should have the property completedAt (base name: "completedAt")', function() {
      // uncomment below and update the code to test the property completedAt
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be();
    });

    it('should have the property progress (base name: "progress")', function() {
      // uncomment below and update the code to test the property progress
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "data")', function() {
      // uncomment below and update the code to test the property data
      //var instance = new Assignments.Assignment();
      //expect(instance).to.be();
    });

  });

}));
