/**
 * Checklists Server API.
 * API to create and read checklists.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dos@redocly.com.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateChecklist201Response model module.
 * @module model/CreateChecklist201Response
 * @version 1.0
 */
class CreateChecklist201Response {
    /**
     * Constructs a new <code>CreateChecklist201Response</code>.
     * @alias module:model/CreateChecklist201Response
     */
    constructor() { 
        
        CreateChecklist201Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateChecklist201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateChecklist201Response} obj Optional instance to populate.
     * @return {module:model/CreateChecklist201Response} The populated <code>CreateChecklist201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateChecklist201Response();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], Object);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], Object);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], Object);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], Object);
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateChecklist201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateChecklist201Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} id
 */
CreateChecklist201Response.prototype['id'] = undefined;

/**
 * @member {Object} name
 */
CreateChecklist201Response.prototype['name'] = undefined;

/**
 * @member {Object} items
 */
CreateChecklist201Response.prototype['items'] = undefined;

/**
 * @member {Object} createdAt
 */
CreateChecklist201Response.prototype['createdAt'] = undefined;

/**
 * @member {Object} updatedAt
 */
CreateChecklist201Response.prototype['updatedAt'] = undefined;






export default CreateChecklist201Response;

