/**
 * Checklists Server API.
 * API to create and read checklists.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dos@redocly.com.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateChecklistRequest model module.
 * @module model/CreateChecklistRequest
 * @version 1.0
 */
class CreateChecklistRequest {
    /**
     * Constructs a new <code>CreateChecklistRequest</code>.
     * @alias module:model/CreateChecklistRequest
     */
    constructor() { 
        
        CreateChecklistRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateChecklistRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateChecklistRequest} obj Optional instance to populate.
     * @return {module:model/CreateChecklistRequest} The populated <code>CreateChecklistRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateChecklistRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], Object);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateChecklistRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateChecklistRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} name
 */
CreateChecklistRequest.prototype['name'] = undefined;

/**
 * @member {Object} items
 */
CreateChecklistRequest.prototype['items'] = undefined;






export default CreateChecklistRequest;

