/**
 * Checklists Server API.
 * API to create and read checklists.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dos@redocly.com.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetCheckLists500Response model module.
 * @module model/GetCheckLists500Response
 * @version 1.0
 */
class GetCheckLists500Response {
    /**
     * Constructs a new <code>GetCheckLists500Response</code>.
     * @alias module:model/GetCheckLists500Response
     */
    constructor() { 
        
        GetCheckLists500Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetCheckLists500Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetCheckLists500Response} obj Optional instance to populate.
     * @return {module:model/GetCheckLists500Response} The populated <code>GetCheckLists500Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetCheckLists500Response();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetCheckLists500Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetCheckLists500Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} message
 */
GetCheckLists500Response.prototype['message'] = undefined;






export default GetCheckLists500Response;

