/**
 * Activities
 * Activities.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostActivitiesRequestData from './PostActivitiesRequestData';
import PostActivitiesRequestMetadata from './PostActivitiesRequestMetadata';

/**
 * The PostActivitiesRequest model module.
 * @module model/PostActivitiesRequest
 * @version 1.0.0
 */
class PostActivitiesRequest {
    /**
     * Constructs a new <code>PostActivitiesRequest</code>.
     * @alias module:model/PostActivitiesRequest
     */
    constructor() { 
        
        PostActivitiesRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostActivitiesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostActivitiesRequest} obj Optional instance to populate.
     * @return {module:model/PostActivitiesRequest} The populated <code>PostActivitiesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostActivitiesRequest();

            if (data.hasOwnProperty('data')) {
                obj['data'] = PostActivitiesRequestData.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = PostActivitiesRequestMetadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostActivitiesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostActivitiesRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          PostActivitiesRequestData.validateJSON(data['data']);
        }
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          PostActivitiesRequestMetadata.validateJSON(data['metadata']);
        }

        return true;
    }


}



/**
 * @member {module:model/PostActivitiesRequestData} data
 */
PostActivitiesRequest.prototype['data'] = undefined;

/**
 * @member {module:model/PostActivitiesRequestMetadata} metadata
 */
PostActivitiesRequest.prototype['metadata'] = undefined;






export default PostActivitiesRequest;

