/**
 * Activities
 * Activities.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostActivities400Response model module.
 * @module model/PostActivities400Response
 * @version 1.0.0
 */
class PostActivities400Response {
    /**
     * Constructs a new <code>PostActivities400Response</code>.
     * @alias module:model/PostActivities400Response
     */
    constructor() { 
        
        PostActivities400Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostActivities400Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostActivities400Response} obj Optional instance to populate.
     * @return {module:model/PostActivities400Response} The populated <code>PostActivities400Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostActivities400Response();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostActivities400Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostActivities400Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} type
 */
PostActivities400Response.prototype['type'] = undefined;

/**
 * @member {Object} title
 */
PostActivities400Response.prototype['title'] = undefined;






export default PostActivities400Response;

