/**
 * Checklists Server API.
 * API to create and read checklists.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dos@redocly.com.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ChecklistsApiSdk);
  }
}(this, function(expect, ChecklistsApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ChecklistsApiSdk.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('createChecklist', function() {
      it('should call createChecklist successfully', function(done) {
        //uncomment below and update the code to test createChecklist
        //instance.createChecklist(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCheckLists', function() {
      it('should call getCheckLists successfully', function(done) {
        //uncomment below and update the code to test getCheckLists
        //instance.getCheckLists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
