/**
 * Assignments
 * API to assign checklist or quiz to user.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: blips-and-chitze@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Assignment from './model/Assignment';
import AssignmentAllOf from './model/AssignmentAllOf';
import CreateAssignment400Response from './model/CreateAssignment400Response';
import CreateAssignmentRequest from './model/CreateAssignmentRequest';
import GetAssignets404Response from './model/GetAssignets404Response';
import NewAssignment from './model/NewAssignment';
import DefaultApi from './api/DefaultApi';


/**
* API to assign checklist or quiz to user..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Assignments = require('index'); // See note below*.
* var xxxSvc = new Assignments.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Assignments.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Assignments.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Assignments.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Assignment model constructor.
     * @property {module:model/Assignment}
     */
    Assignment,

    /**
     * The AssignmentAllOf model constructor.
     * @property {module:model/AssignmentAllOf}
     */
    AssignmentAllOf,

    /**
     * The CreateAssignment400Response model constructor.
     * @property {module:model/CreateAssignment400Response}
     */
    CreateAssignment400Response,

    /**
     * The CreateAssignmentRequest model constructor.
     * @property {module:model/CreateAssignmentRequest}
     */
    CreateAssignmentRequest,

    /**
     * The GetAssignets404Response model constructor.
     * @property {module:model/GetAssignets404Response}
     */
    GetAssignets404Response,

    /**
     * The NewAssignment model constructor.
     * @property {module:model/NewAssignment}
     */
    NewAssignment,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
