/**
 * Assignments
 * API to assign checklist or quiz to user.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: blips-and-chitze@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssignmentAllOf model module.
 * @module model/AssignmentAllOf
 * @version 0.0.1
 */
class AssignmentAllOf {
    /**
     * Constructs a new <code>AssignmentAllOf</code>.
     * @alias module:model/AssignmentAllOf
     */
    constructor() { 
        
        AssignmentAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssignmentAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssignmentAllOf} obj Optional instance to populate.
     * @return {module:model/AssignmentAllOf} The populated <code>AssignmentAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssignmentAllOf();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('assignedAt')) {
                obj['assignedAt'] = ApiClient.convertToType(data['assignedAt'], 'Date');
            }
            if (data.hasOwnProperty('completedAt')) {
                obj['completedAt'] = ApiClient.convertToType(data['completedAt'], 'Date');
            }
            if (data.hasOwnProperty('progress')) {
                obj['progress'] = ApiClient.convertToType(data['progress'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssignmentAllOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssignmentAllOf</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * Assignment ID.
 * @member {String} id
 */
AssignmentAllOf.prototype['id'] = undefined;

/**
 * Timestamp when assigned.
 * @member {Date} assignedAt
 */
AssignmentAllOf.prototype['assignedAt'] = undefined;

/**
 * Timestamp when completed.
 * @member {Date} completedAt
 */
AssignmentAllOf.prototype['completedAt'] = undefined;

/**
 * Progress in `percent`.
 * @member {Number} progress
 */
AssignmentAllOf.prototype['progress'] = undefined;

/**
 * Status of assignment.
 * @member {String} status
 */
AssignmentAllOf.prototype['status'] = undefined;

/**
 * Assignment data.
 * @member {Object} data
 */
AssignmentAllOf.prototype['data'] = undefined;






export default AssignmentAllOf;

