/**
 * Assignments
 * API to assign checklist or quiz to user.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: blips-and-chitze@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssignmentAllOf from './AssignmentAllOf';
import NewAssignment from './NewAssignment';

/**
 * The Assignment model module.
 * @module model/Assignment
 * @version 0.0.1
 */
class Assignment {
    /**
     * Constructs a new <code>Assignment</code>.
     * Representation of a assignment.
     * @alias module:model/Assignment
     * @implements module:model/NewAssignment
     * @implements module:model/AssignmentAllOf
     */
    constructor() { 
        NewAssignment.initialize(this);AssignmentAllOf.initialize(this);
        Assignment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Assignment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Assignment} obj Optional instance to populate.
     * @return {module:model/Assignment} The populated <code>Assignment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Assignment();
            NewAssignment.constructFromObject(data, obj);
            AssignmentAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], 'Date');
            }
            if (data.hasOwnProperty('maxAttempts')) {
                obj['maxAttempts'] = ApiClient.convertToType(data['maxAttempts'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('assignedAt')) {
                obj['assignedAt'] = ApiClient.convertToType(data['assignedAt'], 'Date');
            }
            if (data.hasOwnProperty('completedAt')) {
                obj['completedAt'] = ApiClient.convertToType(data['completedAt'], 'Date');
            }
            if (data.hasOwnProperty('progress')) {
                obj['progress'] = ApiClient.convertToType(data['progress'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Assignment</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Assignment</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['user'] && !(typeof data['user'] === 'string' || data['user'] instanceof String)) {
            throw new Error("Expected the field `user` to be a primitive type in the JSON string but got " + data['user']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * Assignment user.
 * @member {String} user
 */
Assignment.prototype['user'] = undefined;

/**
 * Assignment name.
 * @member {String} name
 */
Assignment.prototype['name'] = undefined;

/**
 * @member {module:model/Assignment.TypeEnum} type
 */
Assignment.prototype['type'] = undefined;

/**
 * Timestamp with deadline.
 * @member {Date} deadline
 */
Assignment.prototype['deadline'] = undefined;

/**
 * Max attemps for assignmet.
 * @member {Number} maxAttempts
 */
Assignment.prototype['maxAttempts'] = undefined;

/**
 * Assignment ID.
 * @member {String} id
 */
Assignment.prototype['id'] = undefined;

/**
 * Timestamp when assigned.
 * @member {Date} assignedAt
 */
Assignment.prototype['assignedAt'] = undefined;

/**
 * Timestamp when completed.
 * @member {Date} completedAt
 */
Assignment.prototype['completedAt'] = undefined;

/**
 * Progress in `percent`.
 * @member {Number} progress
 */
Assignment.prototype['progress'] = undefined;

/**
 * Status of assignment.
 * @member {String} status
 */
Assignment.prototype['status'] = undefined;

/**
 * Assignment data.
 * @member {Object} data
 */
Assignment.prototype['data'] = undefined;


// Implement NewAssignment interface:
/**
 * Assignment user.
 * @member {String} user
 */
NewAssignment.prototype['user'] = undefined;
/**
 * Assignment name.
 * @member {String} name
 */
NewAssignment.prototype['name'] = undefined;
/**
 * @member {module:model/NewAssignment.TypeEnum} type
 */
NewAssignment.prototype['type'] = undefined;
/**
 * Timestamp with deadline.
 * @member {Date} deadline
 */
NewAssignment.prototype['deadline'] = undefined;
/**
 * Max attemps for assignmet.
 * @member {Number} maxAttempts
 */
NewAssignment.prototype['maxAttempts'] = undefined;
// Implement AssignmentAllOf interface:
/**
 * Assignment ID.
 * @member {String} id
 */
AssignmentAllOf.prototype['id'] = undefined;
/**
 * Timestamp when assigned.
 * @member {Date} assignedAt
 */
AssignmentAllOf.prototype['assignedAt'] = undefined;
/**
 * Timestamp when completed.
 * @member {Date} completedAt
 */
AssignmentAllOf.prototype['completedAt'] = undefined;
/**
 * Progress in `percent`.
 * @member {Number} progress
 */
AssignmentAllOf.prototype['progress'] = undefined;
/**
 * Status of assignment.
 * @member {String} status
 */
AssignmentAllOf.prototype['status'] = undefined;
/**
 * Assignment data.
 * @member {Object} data
 */
AssignmentAllOf.prototype['data'] = undefined;



/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Assignment['TypeEnum'] = {

    /**
     * value: "quiz"
     * @const
     */
    "quiz": "quiz",

    /**
     * value: "checklist"
     * @const
     */
    "checklist": "checklist"
};



export default Assignment;

