/**
 * Checklists Server API.
 * API to create and read checklists.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dos@redocly.com.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateChecklist201Response from './model/CreateChecklist201Response';
import CreateChecklistRequest from './model/CreateChecklistRequest';
import GetCheckLists401Response from './model/GetCheckLists401Response';
import GetCheckLists500Response from './model/GetCheckLists500Response';
import DefaultApi from './api/DefaultApi';


/**
* API to create and read checklists..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ChecklistsApiSdk = require('index'); // See note below*.
* var xxxSvc = new ChecklistsApiSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ChecklistsApiSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ChecklistsApiSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ChecklistsApiSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateChecklist201Response model constructor.
     * @property {module:model/CreateChecklist201Response}
     */
    CreateChecklist201Response,

    /**
     * The CreateChecklistRequest model constructor.
     * @property {module:model/CreateChecklistRequest}
     */
    CreateChecklistRequest,

    /**
     * The GetCheckLists401Response model constructor.
     * @property {module:model/GetCheckLists401Response}
     */
    GetCheckLists401Response,

    /**
     * The GetCheckLists500Response model constructor.
     * @property {module:model/GetCheckLists500Response}
     */
    GetCheckLists500Response,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
