/**
 * Impossible Missions Force Reports
 * Reports API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetUsersSummary404Response model module.
 * @module model/GetUsersSummary404Response
 * @version 1.0.0
 */
class GetUsersSummary404Response {
    /**
     * Constructs a new <code>GetUsersSummary404Response</code>.
     * @alias module:model/GetUsersSummary404Response
     */
    constructor() { 
        
        GetUsersSummary404Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetUsersSummary404Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetUsersSummary404Response} obj Optional instance to populate.
     * @return {module:model/GetUsersSummary404Response} The populated <code>GetUsersSummary404Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetUsersSummary404Response();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], Object);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetUsersSummary404Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetUsersSummary404Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} type
 */
GetUsersSummary404Response.prototype['type'] = undefined;

/**
 * @member {Object} message
 */
GetUsersSummary404Response.prototype['message'] = undefined;

/**
 * @member {Object} title
 */
GetUsersSummary404Response.prototype['title'] = undefined;






export default GetUsersSummary404Response;

