/**
 * Impossible Missions Force Reports
 * Reports API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SummaryReports model module.
 * @module model/SummaryReports
 * @version 1.0.0
 */
class SummaryReports {
    /**
     * Constructs a new <code>SummaryReports</code>.
     * @alias module:model/SummaryReports
     */
    constructor() { 
        
        SummaryReports.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SummaryReports</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SummaryReports} obj Optional instance to populate.
     * @return {module:model/SummaryReports} The populated <code>SummaryReports</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SummaryReports();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], Object);
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], Object);
            }
            if (data.hasOwnProperty('endDate')) {
                obj['endDate'] = ApiClient.convertToType(data['endDate'], Object);
            }
            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], Object);
            }
            if (data.hasOwnProperty('attempts')) {
                obj['attempts'] = ApiClient.convertToType(data['attempts'], Object);
            }
            if (data.hasOwnProperty('quizzes')) {
                obj['quizzes'] = ApiClient.convertToType(data['quizzes'], Object);
            }
            if (data.hasOwnProperty('passRate')) {
                obj['passRate'] = ApiClient.convertToType(data['passRate'], Object);
            }
            if (data.hasOwnProperty('checklists')) {
                obj['checklists'] = ApiClient.convertToType(data['checklists'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SummaryReports</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SummaryReports</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} id
 */
SummaryReports.prototype['id'] = undefined;

/**
 * @member {Object} startDate
 */
SummaryReports.prototype['startDate'] = undefined;

/**
 * @member {Object} endDate
 */
SummaryReports.prototype['endDate'] = undefined;

/**
 * @member {Object} users
 */
SummaryReports.prototype['users'] = undefined;

/**
 * @member {Object} attempts
 */
SummaryReports.prototype['attempts'] = undefined;

/**
 * @member {Object} quizzes
 */
SummaryReports.prototype['quizzes'] = undefined;

/**
 * @member {Object} passRate
 */
SummaryReports.prototype['passRate'] = undefined;

/**
 * @member {Object} checklists
 */
SummaryReports.prototype['checklists'] = undefined;






export default SummaryReports;

