/**
 * Impossible Missions Force Reports
 * Reports API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsersById model module.
 * @module model/UsersById
 * @version 1.0.0
 */
class UsersById {
    /**
     * Constructs a new <code>UsersById</code>.
     * @alias module:model/UsersById
     * @extends Object
     */
    constructor() { 
        
        UsersById.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersById</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersById} obj Optional instance to populate.
     * @return {module:model/UsersById} The populated <code>UsersById</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersById();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], Object);
            }
            if (data.hasOwnProperty('badges')) {
                obj['badges'] = ApiClient.convertToType(data['badges'], Object);
            }
            if (data.hasOwnProperty('assignments')) {
                obj['assignments'] = ApiClient.convertToType(data['assignments'], Object);
            }
            if (data.hasOwnProperty('activity')) {
                obj['activity'] = ApiClient.convertToType(data['activity'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersById</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersById</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} id
 */
UsersById.prototype['id'] = undefined;

/**
 * @member {Object} badges
 */
UsersById.prototype['badges'] = undefined;

/**
 * @member {Object} assignments
 */
UsersById.prototype['assignments'] = undefined;

/**
 * @member {Object} activity
 */
UsersById.prototype['activity'] = undefined;






export default UsersById;

