/**
 * Impossible Missions Force Reports
 * Reports API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ImpossibleMissionsForceReports);
  }
}(this, function(expect, ImpossibleMissionsForceReports) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ImpossibleMissionsForceReports.SummaryReports();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SummaryReports', function() {
    it('should create an instance of SummaryReports', function() {
      // uncomment below and update the code to test SummaryReports
      //var instance = new ImpossibleMissionsForceReports.SummaryReports();
      //expect(instance).to.be.a(ImpossibleMissionsForceReports.SummaryReports);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ImpossibleMissionsForceReports.SummaryReports();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "startDate")', function() {
      // uncomment below and update the code to test the property startDate
      //var instance = new ImpossibleMissionsForceReports.SummaryReports();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "endDate")', function() {
      // uncomment below and update the code to test the property endDate
      //var instance = new ImpossibleMissionsForceReports.SummaryReports();
      //expect(instance).to.be();
    });

    it('should have the property users (base name: "users")', function() {
      // uncomment below and update the code to test the property users
      //var instance = new ImpossibleMissionsForceReports.SummaryReports();
      //expect(instance).to.be();
    });

    it('should have the property attempts (base name: "attempts")', function() {
      // uncomment below and update the code to test the property attempts
      //var instance = new ImpossibleMissionsForceReports.SummaryReports();
      //expect(instance).to.be();
    });

    it('should have the property quizzes (base name: "quizzes")', function() {
      // uncomment below and update the code to test the property quizzes
      //var instance = new ImpossibleMissionsForceReports.SummaryReports();
      //expect(instance).to.be();
    });

    it('should have the property passRate (base name: "passRate")', function() {
      // uncomment below and update the code to test the property passRate
      //var instance = new ImpossibleMissionsForceReports.SummaryReports();
      //expect(instance).to.be();
    });

    it('should have the property checklists (base name: "checklists")', function() {
      // uncomment below and update the code to test the property checklists
      //var instance = new ImpossibleMissionsForceReports.SummaryReports();
      //expect(instance).to.be();
    });

  });

}));
