/**
 * Impossible Missions Force Reports
 * Reports API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ImpossibleMissionsForceReports);
  }
}(this, function(expect, ImpossibleMissionsForceReports) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ImpossibleMissionsForceReports.UsersById();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersById', function() {
    it('should create an instance of UsersById', function() {
      // uncomment below and update the code to test UsersById
      //var instance = new ImpossibleMissionsForceReports.UsersById();
      //expect(instance).to.be.a(ImpossibleMissionsForceReports.UsersById);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ImpossibleMissionsForceReports.UsersById();
      //expect(instance).to.be();
    });

    it('should have the property badges (base name: "badges")', function() {
      // uncomment below and update the code to test the property badges
      //var instance = new ImpossibleMissionsForceReports.UsersById();
      //expect(instance).to.be();
    });

    it('should have the property assignments (base name: "assignments")', function() {
      // uncomment below and update the code to test the property assignments
      //var instance = new ImpossibleMissionsForceReports.UsersById();
      //expect(instance).to.be();
    });

    it('should have the property activity (base name: "activity")', function() {
      // uncomment below and update the code to test the property activity
      //var instance = new ImpossibleMissionsForceReports.UsersById();
      //expect(instance).to.be();
    });

  });

}));
