/**
 * Checklists Server API.
 * API to create and read checklists.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dos@redocly.com.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateChecklist201Response from '../model/CreateChecklist201Response';
import CreateChecklistRequest from '../model/CreateChecklistRequest';
import GetCheckLists401Response from '../model/GetCheckLists401Response';
import GetCheckLists500Response from '../model/GetCheckLists500Response';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createChecklist operation.
     * @callback module:api/DefaultApi~createChecklistCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateChecklist201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Checklist
     * Create checklist.
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateChecklistRequest} opts.createChecklistRequest 
     * @param {module:api/DefaultApi~createChecklistCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateChecklist201Response}
     */
    createChecklist(opts, callback) {
      opts = opts || {};
      let postBody = opts['createChecklistRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/problem+json', 'application/json'];
      let returnType = CreateChecklist201Response;
      return this.apiClient.callApi(
        '/checklists', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCheckLists operation.
     * @callback module:api/DefaultApi~getCheckListsCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Checklists
     * Get the list of checklists.
     * @param {module:api/DefaultApi~getCheckListsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getCheckLists(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/problem+json', 'application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/checklists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
