/**
 * Badges
 * Badges API allows you to create Badges rules that can be applied to particular users.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@impossiblemissionsforce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RequirementInner from './RequirementInner';

/**
 * The PostBadgesRequest model module.
 * @module model/PostBadgesRequest
 * @version v1
 */
class PostBadgesRequest {
    /**
     * Constructs a new <code>PostBadgesRequest</code>.
     * @alias module:model/PostBadgesRequest
     */
    constructor() { 
        
        PostBadgesRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostBadgesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostBadgesRequest} obj Optional instance to populate.
     * @return {module:model/PostBadgesRequest} The populated <code>PostBadgesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostBadgesRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
            if (data.hasOwnProperty('requirements')) {
                obj['requirements'] = ApiClient.convertToType(data['requirements'], [RequirementInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostBadgesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostBadgesRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['icon'] && !(typeof data['icon'] === 'string' || data['icon'] instanceof String)) {
            throw new Error("Expected the field `icon` to be a primitive type in the JSON string but got " + data['icon']);
        }
        if (data['requirements']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['requirements'])) {
                throw new Error("Expected the field `requirements` to be an array in the JSON data but got " + data['requirements']);
            }
            // validate the optional field `requirements` (array)
            for (const item of data['requirements']) {
                RequirementInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} name
 */
PostBadgesRequest.prototype['name'] = undefined;

/**
 * @member {String} icon
 */
PostBadgesRequest.prototype['icon'] = undefined;

/**
 * @member {Array.<module:model/RequirementInner>} requirements
 */
PostBadgesRequest.prototype['requirements'] = undefined;






export default PostBadgesRequest;

