/**
 * Badges
 * Badges API allows you to create Badges rules that can be applied to particular users.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@impossiblemissionsforce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequirementInner model module.
 * @module model/RequirementInner
 * @version v1
 */
class RequirementInner {
    /**
     * Constructs a new <code>RequirementInner</code>.
     * @alias module:model/RequirementInner
     */
    constructor() { 
        
        RequirementInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RequirementInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequirementInner} obj Optional instance to populate.
     * @return {module:model/RequirementInner} The populated <code>RequirementInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequirementInner();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('minScore')) {
                obj['minScore'] = ApiClient.convertToType(data['minScore'], 'Number');
            }
            if (data.hasOwnProperty('maxAttempts')) {
                obj['maxAttempts'] = ApiClient.convertToType(data['maxAttempts'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RequirementInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RequirementInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {String} type
 */
RequirementInner.prototype['type'] = undefined;

/**
 * @member {String} name
 */
RequirementInner.prototype['name'] = undefined;

/**
 * @member {Number} minScore
 */
RequirementInner.prototype['minScore'] = undefined;

/**
 * @member {Number} maxAttempts
 */
RequirementInner.prototype['maxAttempts'] = undefined;

/**
 * @member {module:model/RequirementInner.StatusEnum} status
 */
RequirementInner.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
RequirementInner['StatusEnum'] = {

    /**
     * value: "done"
     * @const
     */
    "done": "done",

    /**
     * value: "new"
     * @const
     */
    "new": "new"
};



export default RequirementInner;

