/**
 * Scores API
 * Scores API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ScoresApi);
  }
}(this, function(expect, ScoresApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ScoresApi.Breakdown();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Breakdown', function() {
    it('should create an instance of Breakdown', function() {
      // uncomment below and update the code to test Breakdown
      //var instance = new ScoresApi.Breakdown();
      //expect(instance).to.be.a(ScoresApi.Breakdown);
    });

    it('should have the property question (base name: "question")', function() {
      // uncomment below and update the code to test the property question
      //var instance = new ScoresApi.Breakdown();
      //expect(instance).to.be();
    });

    it('should have the property choices (base name: "choices")', function() {
      // uncomment below and update the code to test the property choices
      //var instance = new ScoresApi.Breakdown();
      //expect(instance).to.be();
    });

    it('should have the property correctAnswer (base name: "correctAnswer")', function() {
      // uncomment below and update the code to test the property correctAnswer
      //var instance = new ScoresApi.Breakdown();
      //expect(instance).to.be();
    });

    it('should have the property answer (base name: "answer")', function() {
      // uncomment below and update the code to test the property answer
      //var instance = new ScoresApi.Breakdown();
      //expect(instance).to.be();
    });

    it('should have the property answeredAt (base name: "answeredAt")', function() {
      // uncomment below and update the code to test the property answeredAt
      //var instance = new ScoresApi.Breakdown();
      //expect(instance).to.be();
    });

  });

}));
