/**
 * Activities
 * Activities.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PostActivities400Response from '../model/PostActivities400Response';
import PostActivitiesRequest from '../model/PostActivitiesRequest';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the postActivities operation.
     * @callback module:api/DefaultApi~postActivitiesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new activity
     * @param {module:model/PostActivitiesRequest} postActivitiesRequest 
     * @param {module:api/DefaultApi~postActivitiesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postActivities(postActivitiesRequest, callback) {
      let postBody = postActivitiesRequest;
      // verify the required parameter 'postActivitiesRequest' is set
      if (postActivitiesRequest === undefined || postActivitiesRequest === null) {
        throw new Error("Missing the required parameter 'postActivitiesRequest' when calling postActivities");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['IMF-KEY'];
      let contentTypes = ['application/json'];
      let accepts = ['application/problem+json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/activities', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
